### ISSUE TITLE
Error when minified

### ISSUE THREAD

**Issue by stefan-leye** [GerHobbelt/jison#7]
When minifying jison (and most  sepecifically the regexp-lexer.js) an error is thrown when executing the parser generator. 
Basically, there seems to be a problem with the minified lexer function, that is translated to a string and back.
The error happens here:
https://github.com/GerHobbelt/jison/blob/master/lib/util/regexp-lexer.js#L1043

I tested it with minification by uglify and goolge-closure.

It would be great, if there was a fix for that.

**Comment by GerHobbelt** [comment]
regexp-lexer.js is a compiler and not really meant to be 'uglified' as it should run in a developer environment only, so I wonder what your use case is, where you want/need to uglify/compress this particular file.

(The *generated code* on the other hand, i.e. the generated lexer, *is* meant to be minified as it would be running in any production environment.)

**Comment by stefan-leye** [comment]
I'm currently working on a web-based project, where users need a highly dynamical filter language. They have to adapt the language (not just the filters themselves) to their needs/work environment. 

To create such languages dynamically, they have to be generated on the client, and the code for that should be minified.

**Comment by GerHobbelt** [comment]
Got it. That's a bit of a challenge. ;-)  Anyway, don't know when I get this fixed; for the time being, I would advise to find a way to make sure the critical code parts don't get obfuscated by the minifier -- my bet is that possibly the JisonLexerError 'class' (a `function`) is minified while it shouldn't as that is a 'global'. But that's just my *guestimate*... what is the actual error / crash report you get?

(Note to self: I could add a 'crash dump' functionality here a la https://github.com/GerHobbelt/jison/commit/85e367d03b977780516d2b643afbe6f65ee758f2 to help us diagnose what *exactly* is causing the `new Function(...)` code to barf a hairball.)

**Comment by GerHobbelt** [comment]
Please check the latest master; the generated code is dumped to file when a crash like that occurs, so that you can diagnose more precisely what went wrong during code generation. 

(run `node \<dumpfile.js\>` to see where the generated code fails exactly. This helps diagnose what went wrong and how in the code generator.)

**Comment by stefan-leye** [comment]
thank you, I will do that asap.

**Comment by stefan-leye** [comment]
After following your instructions I get the following error message:

`function getRegExpLexerPrototype(){return{EOF:1,ERROR:2,__currentRuleSet__:null,__error_infos:[],__decompressed:!1,done:
!1,_backtrack:!1,_input:"",_more:!1,_signaled_error_token:!1,conditionStack:[],match:"",matched:"",matches:!1,yytext:"",
offset:0,yyleng:0,yylineno:0,yylloc:null,constructLexErrorInfo:function(e,r){var n={errStr:e,recoverable:!!r,text:this.m
atch,token:null,line:this.yylineno,loc:this.yylloc,yy:this.yy,lexer:this,destroy:function(){var e=!!this.recoverable;for
(var r in this)this.hasOwnProperty(r)&&"object"==typeof r&&(this[r]=void 0);this.recoverable=e}};return this.__error_inf
os.push(n),n},parseError:function(e,r,n){if(this.yy.parser&&"function"==typeof this.yy.parser.parseError)return this.yy.
parser.parseError(e,r,n)||this.ERROR;if("function"==typeof this.yy.parseError)return this.yy.parseError(e,r,n)||this.ERR
OR;throw new n(e,r)},cleanupAfterLex:function(e){if(this.setInput("",{}),!e){for(var r=this.__error_infos.length-1;r>=0;
r--){var n=this.__error_infos[r];n&
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3`

**Comment by GerHobbelt** [comment]
Hi Stefan,
There's a new master, which should behave a wee bit better (though I don't expect it to pass without a hitch -- long story there); thanks for testing the previous round. Can you run another round with the latest master and tell me what you get (dumpfile + error report)?

BTW: are you using UglifyJS2 or Google Closure Compiler?

**Comment by stefan-leye** [comment]
Here is teh error with the new code:

> dump.js:33
    options: {},
           ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

This is the failing code: [dump.txt](https://github.com/GerHobbelt/jison/files/922422/dump.txt)

P.S. Currently I'm using a Webpack pipeline using the Uglify loader for minification, as only loaders allow me to exclude specific input files. But I'm very keen on switching to the Google Closure Compiler, which I can only do, when all files and libs are minifiable.

**Comment by GerHobbelt** [comment]
Hm, looks like maybe this can help resolve this issue: https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#user-content-nocompile

Will add that as a quick-fix band-aid to the jison lexer and parser engines as only the generated code (lexer and parser produced using user defined grammars) is meant to be used in production environments, i.e. minified form.

**Comment by GerHobbelt** [comment]
release v0.6.1-200 uses a different-enough approach now to code generation that this one might now be feasible. (haven't tested it yet, though!)

**Comment by GerHobbelt** [comment]
@stefan-leye: working on #32 now: this might be of interest to you too as it will make the jison tool itself more amenable to code compressors/rewriters and thus it is expected that once #32 is done, jison should cause minimal or even no trouble for gcc (google closure compiler) either.
